# Generated by Django 3.1.5 on 2021-01-18 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GratefulFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOf', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=120)),
                ('gratefulOf', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SmallVictory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOf', models.DateField(auto_now_add=True)),
                ('user', models.CharField(max_length=120)),
                ('dailyWin', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
